### ISSUE TITLE
Taggings Join Table

### ISSUE THREAD

**Issue by d-webs** [BCrawfordScott/aeterNote#1]
Seems like Taggings is a join table between notes and tags. I would think that the foreign keys in this table would be tag_id and note_id, as opposed to tag_id and user_id. easy fix!

Also, as a bonus down the road, it could be helpful to make this a polymorphic association--the reason being that both notes and notebooks can have tags. We can talk about this more down the line though...

**Comment by BCrawfordScott** [comment]
Awesome, thanks man.  I made the change to the joins table.

In regards to the polymorphic association, I totally hear you. I thought that at first too, but didn't think that notebooks could be tagged.  I'll poke around Evernote some more to figure it out;  I like the idea of having the association to show off.
