### ISSUE TITLE
Schema Feedback

### ISSUE THREAD

**Issue by d-webs** [BCrawfordScott/aeterNote#2]
**Schema Feedback**

- I would put note_ids and notebook_ids in the slice of state for the current user, to be able to easily look up these associated slices. this is generally the approach with how we organize has_many associations on the frontend.

- I notice that many of these slices of state have something called flag_ids. Are these supposed to be tag_ids? On top of this, Tags should live somewhere in your state!

**Comment by BCrawfordScott** [comment]
Great: added the ids and removed the 'flags' that was definitely a mid-week-exhaustion typo and word confusion.  Thanks!
