### ISSUE TITLE
Auth

### ISSUE THREAD

**Issue by d-webs** [BCrawfordScott/aeterNote#3]
- [x]  Successful logout brings you back to full "new session" page

**Comment by BCrawfordScott** [comment]
Hey David, I just pushed my completed auth to heroku. Please check it out when you get a chance.

**Comment by d-webs** [comment]
Looks great! Only small advice would be to style errors a little nicer (more aligned, at least) on the home page

**Comment by BCrawfordScott** [comment]
Will do!
